### ISSUE TITLE
Balloon driver preventing Windows 7 guest from shutting down

### ISSUE THREAD

**Issue by JonathonReinhart** [YanVugenfirer/kvm-guest-drivers-windows#26]
My Windows 7 Utlimate (64-bit) guest hangs at the "(spinner) Shutting down..." screen after clicking Start -> Shutdown.

Uninstalling the Balloon driver allows the guest to fully shut down.

### Host:

Component | Version
---------------|-------------
OS | CentOS 7 x64
Kernel | 3.10.0-123.el7.x86_64
qemu.x86_64 | 2:2.0.0-1.el7.3
virt-manager | 0.10.0-20.el7

### Guest:

Component | Version
---------------|-------------
OS | Windows 7 Ultimate (64-bit)
CPU | QEMU Virtual CPU version 1.5.3 (2 processors)

[virtio-win-0.1-94](http://alt.fedoraproject.org/pub/alt/virtio-win/archives/virtio-win-0.1-94/) drivers installed:
      VirtIO SCSI:     viostor.sys  61.71.104.9400
      VirtIO-Serial:   vioser.sys   61.71.104.9400
      VirtIO Balloon:  balloon.sys  61.71.104.9400
      VirtIO Ethernet: netkvm.sys   61.71.104.9400

**Comment by JonathonReinhart** [comment]
ballon.sys 61.70.104.8100 from [virtio-win-0.1.81](http://alt.fedoraproject.org/pub/alt/virtio-win/archives/virtio-win-0.1-81/) does not seem to exhibit this same behavior; it is able to shut down properly.

That version, however crashed with several bug checks: [0xA: IRQL_NOT_LESS_OR_EQUAL](http://msdn.microsoft.com/en-us/library/windows/hardware/ff560129.aspx) once on boot, and [0xC5: DRIVER_CORRUPTED_EXPOOL](http://msdn.microsoft.com/en-us/library/windows/hardware/ff560192.aspx) at shutdown.

**Comment by YanVugenfirer** [comment]
Hi,

Thanks you for the report. There were recent changes that fixed balloon service misbehaviour that might have cause hang on shutdown.

I will check crashes.

Can you upload mini dump files from the crashes?

Best regards,
Yan.

**Comment by JonathonReinhart** [comment]
Unfortunately, I do not have minidumps for those crashes. For some reason,
Windows never wrote them even though it is configured to do so.

Those crashes though were from 0.1-81, not the latest 0.1-94.  If you still
want them I can try to reproduce.

Also, if you have any idea what I should look for during the shutdown hang
(on 0.1-94), I can try to get this with WinDbg.

Or I can try to get the build environment set up and try the latest from
master or stable.  Unfortunately there is no correlation with the version
numbers and git commits, as there are no tags in git.

On Mon, Jan 5, 2015 at 1:43 AM, Yan Vugenfirer <notifications@github.com>
wrote:

> Hi,
>
> Thanks you for the report. There were recent changes that fixed balloon
> service misbehaviour that might have cause hang on shutdown.
>
> I will check crashes.
>
> Can you upload mini dump files from the crashes?
>
> Best regards,
> Yan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/26#issuecomment-68673533>
> .
>



-- 
Computers are incredibly fast, accurate and stupid. Human beings are
incredibly slow, inaccurate and brilliant. Together they are powerful
beyond imagination.
                                    A. Einstein

**Comment by YanVugenfirer** [comment]
Hi,

I just pushed tags. Sorry for that.

If you look at the stable branch, before each release status.txt is updated
and there is a commit message that looks like "update status file. mm116
<-->b96
<https://github.com/YanVugenfirer/kvm-guest-drivers-windows/commit/16d4b7a6a6a439351b53c3b75efa2a49aa450ff4>
".

b<number> - is the build number that you see in the package name (for
example 0.1-96).
mm<number> - is the tag for this release.

You can also checkout according to the hash of the status.txt update commit.

Best regards,
Yan.

On Mon, Jan 5, 2015 at 10:15 AM, Jonathon Reinhart <notifications@github.com
> wrote:

> Unfortunately, I do not have minidumps for those crashes. For some reason,
> Windows never wrote them even though it is configured to do so.
>
> Those crashes though were from 0.1-81, not the latest 0.1-94. If you still
> want them I can try to reproduce.
>
> Also, if you have any idea what I should look for during the shutdown hang
> (on 0.1-94), I can try to get this with WinDbg.
>
> Or I can try to get the build environment set up and try the latest from
> master or stable. Unfortunately there is no correlation with the version
> numbers and git commits, as there are no tags in git.
>
> On Mon, Jan 5, 2015 at 1:43 AM, Yan Vugenfirer <notifications@github.com>
> wrote:
>
> > Hi,
> >
> > Thanks you for the report. There were recent changes that fixed balloon
> > service misbehaviour that might have cause hang on shutdown.
> >
> > I will check crashes.
> >
> > Can you upload mini dump files from the crashes?
> >
> > Best regards,
> > Yan.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/26#issuecomment-68673533>
>
> > .
> >
>
>
>
> --
> Computers are incredibly fast, accurate and stupid. Human beings are
> incredibly slow, inaccurate and brilliant. Together they are powerful
> beyond imagination.
> A. Einstein
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/26#issuecomment-68678730>
> .
>



-- 
-----------------------------------------------------------------------
Daynix Computing LTD
Yan Vugenfirer, CEO
Email: yan@daynix.com
Phone (Israel): +972-54-4758084
Phone (USA): +1-7204776716
Phone (UK): +44-2070482938
Web: www.daynix.com

**Comment by hammerg** [comment]
This sound like a bug that was already solved (but no build which include the fix was released yet).

Does the bug reproduce if you disable the balloon service and not the driver?

Thanks, Gal.

**Comment by JonathonReinhart** [comment]
Manually stopping the BalloonService times out:

  Error 1053: The service did not respond to the start or control request
in a timely fashion.

However, after that attempt at stopping the service, and then changing the
service to Disabled, I *was* able to shut down the machine successfully (on
that same boot).

And unsurprisingly, after the next boot (BallonService still Disabled), I
was again able to shut down successfully.

So yes, disabling BootService allows me to shut down successfully, while
enabling it prevents a full shutdown.


On Mon, Jan 5, 2015 at 4:18 AM, hammerg <notifications@github.com> wrote:

> This sound like a bug that was already solved (but no build which include
> the fix was released yet).
>
> Does the bug reproduce if you disable the balloon service and not the
> driver?
>
> Thanks, Gal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YanVugenfirer/kvm-guest-drivers-windows/issues/26#issuecomment-68683803>
> .
>



-- 
Computers are incredibly fast, accurate and stupid. Human beings are
incredibly slow, inaccurate and brilliant. Together they are powerful
beyond imagination.
                                    A. Einstein

**Comment by hammerg** [comment]
I think that commit 5f7a25c0 is the one that is expcted to resolve this.

**Comment by JonathonReinhart** [comment]
I'd be happy to try this out tomorrow evening (EST). Would one of you be able to provide an updated build? (.sys and .exe, I'm assuming.) Otherwise it may take me longer to get the build environment set up.

**Comment by hammerg** [comment]
I can give you an unofficial build of the balloon service (exe).

**Comment by JonathonReinhart** [comment]
My email address is now on [my profile page](https://github.com/JonathonReinhart).

**Comment by hammerg** [comment]
I've send you an email with the balloon service attached.

**Comment by hammerg** [comment]
It will probably won't solve your problem. I was able to reproduce this bug on my setup and the bug was in the driver's code. A patch was posted.

**Comment by JonathonReinhart** [comment]
I can confirm that the build of balloon service that @hammerg  sent me,  based on commit 0558b0d0b8, works; I am able to fully shut down the guest. :thumbsup:

This is with the latest release of VirtIO Balloon driver 61.71.104.9400.

For reference, this is with `amd64\blnsvr.exe`, with build date of `Mon Jan  5 04:54:53 2015` and SHA1 of
009481149ad127e42c58f005297f91128ddd321b.

**Comment by hammerg** [comment]
Yep. Good timing! :-) Thanks for the verification.

I got consfused between two similar bugs. This bug happens when you shutdown Windows and it was fixed in commit 0558b0d. The second bug which I mentioned in my previous comment occurs when you put the guest to sleep or hibernate.

**Comment by JonathonReinhart** [comment]
That commit is just debug. I think you meant 5f7a25c0c269258bc08dc3b1eeca2701455db9c6.

**Comment by hammerg** [comment]
Yes, you are right, 5f7a25c. Seems like I need one more cup of coffee.

**Comment by JonathonReinhart** [comment]
This is fixed by 5f7a25c0c269258bc08dc3b1eeca2701455db9c6.

**Comment by GioMac** [comment]
Still, I confirm exactly same issue for Windows 2008 R2:
balloon driver from virtio-win-0.1-74.iso - works
balloon driver from virtio-win-0.1.96.iso - spinner on shutdown
virtio-win-0.1.96.iso is in "stable" tree.
Not solved?

**Comment by hammerg** [comment]
That patch which fixed the bug is included from build 99.

**Comment by GioMac** [comment]
Is there any mailing list for Fedora where stable tree for isos issues are discussed or solved? Looks like there is broken iso shipped as stable.
